language: node_js
node_js:
  - "4.4"
before_install:
    - rvm install 2.2.2
    - gem install sass
    - gem install scss_lint
    - npm install -g grunt-cli 
install: npm install
before_script: 
    - grunt compile